### ISSUE TITLE
Bifurkate.com inaccessible

### ISSUE THREAD

**Issue by T1960CT** [fredbegin11/bifurkate#9]
Hello, I use this app frequently through the hosted version, but as of a week or two ago it either gives ERR_CONNECTION_CLOSED when going through HTTPS, and a GoDaddy Parked Domain when going through HTTP - tried on multiple devices with cache cleared on all.

Was the domain not renewed, or is the project being shelved? 

Thanks!

**Comment by glynternet** [comment]
Same here. A couple of days ago I was recommending it to a friend and pulled up the page to see the parked page.

Would love to see it up again.

**Comment by fredbegin11** [comment]
Hey guys! I was planning on shutting it down since the hosting fee is not cheap but I didn't realise people we're still using it. You guys reaching out means there's probably more people using it. 

I'm cycling right now but I'll get it back online as soon as I get home. It should be up in 4-5 hours if everything goes well.

Thanks for your support and sorry for the inconvenience!

**Comment by T1960CT** [comment]
Definitely appreciated! I do 3 or 4 large activities per week and bifurkate is a big part of the planning and seasonal stat tracking. 

Is there anywhere we can contribute a couple bucks here and there to support the project?

**Comment by fredbegin11** [comment]
Hey! Sorry it took me more time than I thought, but Bifurkate is now back online!

I switched from Heroku to Netlify and I believe Netlify's free plan will be more than enough. Everything should be back to normal now, but if you encounter bugs, slowness or weird behaviors, feel free to open another issue!

P.S.: There's a "Buy me a beer" link in the menu if you want to contribute!

Cheers!

**Comment by glynternet** [comment]
Thank you @fredbegin11 !
I just sent some beer money over, really appreciate this resource.
